server:
  port: 8080

servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
    force-request: true
    force-response: true

spring:
  application:
    name: wolof-transliteration

app:
  cors:
    allowed-origins: "http://localhost:4200"

logging:
  level:
    com.wolof: DEBUG
    org.springframework.web: INFO