server:
  port: 8080 # Port du serveur Spring Boot
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

spring:
  application:
    name: wolof-transliteration

# Configuration CORS : autorise les requêtes Angular (port 4200)
app:
  cors:
    allowed-origins: "http://localhost:4200,https://insight-nationally-involve-speeches.trycloudflare.com"
    
# Logs : INFO pour voir les requêtes, DEBUG pour le détail
logging:
  level:
    com.wolof: DEBUG
    org.springframework.web: INFO
